project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Curso de posgrado: Gráficos con ggplot2 2026"
  favicon: imgs/favicon.png
  back-to-top-navigation: true
  reader-mode: false
  bread-crumbs: false
  page-footer: "<span class='footer-space'>Doctorado en Ciencias Biológicas | FCEFyN - UNC</span>"
  navbar:
    background: "#53868B"
    left:
      - href: index.qmd
        text: Inicio
      - href: curso_completo/curso_completo.qmd
        text: Curso completo
      - text: Recursos útiles
        menu:
          - text: R for Data Science
            href: https://r4ds.had.co.nz/
            target: "_blank"
          - text: The R Graph Gallery
            href: https://r-graph-gallery.com
            target: "_blank"
          - text: R Charts
            href: https://r-charts.com/
            target: "_blank"
          - text: R Charts Colors
            href: https://r-charts.com/colors/
            target: "_blank"


format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: true
    toc: true
    toc-location: left
    toc-depth: 3
    toc-title: "Contenidos"
    number-sections: true
    number-depth: 3
    

editor: visual